# Copyright (C) 2016 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/milletwifi/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/milletwifi/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/samsung/milletwifi/proprietary/bin/rfs_access:system/bin/rfs_access \
    vendor/samsung/milletwifi/proprietary/bin/rild:system/bin/rild \
    vendor/samsung/milletwifi/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/samsung/milletwifi/proprietary/etc/clatd.conf:system/etc/clatd.conf \
    vendor/samsung/milletwifi/proprietary/etc/gps.conf:system/etc/gps.conf \
    vendor/samsung/milletwifi/proprietary/etc/izat.conf:system/etc/izat.conf \
    vendor/samsung/milletwifi/proprietary/etc/sap.conf:system/etc/sap.conf \
    vendor/samsung/milletwifi/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    vendor/samsung/milletwifi/proprietary/lib/libloc_eng.so:system/lib/libloc_eng.so \
    vendor/samsung/milletwifi/proprietary/lib/libmdmdetect.so:system/lib/libmdmdetect.so \
    vendor/samsung/milletwifi/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
    vendor/samsung/milletwifi/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/samsung/milletwifi/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
    vendor/samsung/milletwifi/proprietary/vendor/lib/hw/flp.default.so:system/vendor/lib/hw/flp.default.so \
    vendor/samsung/milletwifi/proprietary/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
    vendor/samsung/milletwifi/proprietary/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
	vendor/samsung/milletwifi/proprietary/lib/hw/consumerir.default.so:system/lib/hw/consumerir.default.so
    
