# Copyright (C) 2014-2016 The CyanogenMod Project
# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/millet3g/setup-makefiles.sh

PRODUCT_COPY_FILES += \
vendor/samsung/millet3g/proprietary/bin/qmuxd:system/bin/qmuxd \
vendor/samsung/millet3g/proprietary/bin/radish:system/bin/radish \
vendor/samsung/millet3g/proprietary/bin/rfs_access:system/bin/rfs_access \
vendor/samsung/millet3g/proprietary/bin/rild:system/bin/rild \
vendor/samsung/millet3g/proprietary/bin/rmt_storage:system/bin/rmt_storage \
vendor/samsung/millet3g/proprietary/lib/libmdmdetect.so:system/lib/libmdmdetect.so \
vendor/samsung/millet3g/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
vendor/samsung/millet3g/proprietary/lib/libril.so:system/lib/libril.so \
vendor/samsung/millet3g/proprietary/lib/librilutils.so:system/lib/librilutils.so \
vendor/samsung/millet3g/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
vendor/samsung/millet3g/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
vendor/samsung/millet3g/proprietary/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
vendor/samsung/millet3g/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
vendor/samsung/millet3g/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
vendor/samsung/millet3g/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
vendor/samsung/millet3g/proprietary/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
vendor/samsung/millet3g/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
vendor/samsung/millet3g/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
vendor/samsung/millet3g/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
vendor/samsung/millet3g/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
vendor/samsung/millet3g/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
vendor/samsung/millet3g/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
vendor/samsung/millet3g/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
vendor/samsung/millet3g/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
vendor/samsung/millet3g/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so
vendor/samsung/millet3g/proprietary/vendor/lib/libqmi_csvt_srvc.so:system/vendor/lib/libqmi_csvt_srvc.so
